import { readFile } from "fs/promises";
import { join } from "path";

export async function GET() {
  try {
    // Snapshot is generated by prebuild and bundled into the web app
    // (read from web/data/ instead of ../data/ because Vercel serverless
    // cannot reliably resolve cwd-relative paths outside the bundle).
    const modelPath = join(process.cwd(), "data", "cognitive-model-snapshot.json");
    const raw = await readFile(modelPath, "utf-8");
    const model = JSON.parse(raw);
    return Response.json(model);
  } catch {
    return Response.json({ error: "无法加载认知模型" }, { status: 500 });
  }
}
