import { readFile } from "fs/promises";
import { join } from "path";

/**
 * Serves contradictions from the prebuild snapshot.
 * The snapshot is generated by `scripts/build-contradictions-snapshot.mjs`
 * during `npm run prebuild` and lives inside the web/ bundle.
 */
const SNAPSHOT_PATH = join(process.cwd(), "data", "contradictions-snapshot.json");

export async function GET() {
  try {
    const raw = await readFile(SNAPSHOT_PATH, "utf-8");
    const snapshot = JSON.parse(raw);
    return Response.json(snapshot);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return Response.json({ error: message }, { status: 500 });
  }
}
